version: "3.5"

services:
  app:
    container_name: symfony_internship_app
    hostname: symfony_internship_app
    env_file:
      - .env
    build:
      context: docker/php
      dockerfile: Dockerfile
      args:
        - APP_ENV
        - ENABLE_BUILTIN_SSH
        - LOCAL_UID
        - LOCAL_GID
        - APP_USER
        - APP_GROUP
        - LOGS_IN_CONTAINER
    ports:
      - "${APP_SSH_PORT}:22"
    volumes:
      - ./app:/var/www/symfony:rw
      - ./docker/php/php.overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    links:
      - postgres

  postgres:
    container_name: symfony_internship_postgres
    env_file:
      - .env
    build:
      context: docker/postgres
      dockerfile: Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  nginx:
    container_name: symfony_internship_nginx
    hostname: symfony_internship_nginx
    image: library/nginx:1.19.5
    volumes:
      - ./docker/nginx/vhosts:/etc/nginx/vhosts
      - ./app:/var/www/symfony:rw
      - ./docker/nginx/nginx_dev.conf:/etc/nginx/nginx.conf
    ports:
      - "${NGINX_PORT}:80"
    links:
      - app

volumes:
  pgdata:
